---
title: "Participation 1-30-2020"
author: "Kaitlin"
date: "1/30/2020"
output: html_document
---

```{r}
#install.packages("tidyverse")
#install.packages("scales")
#install.packages("tsibble")

suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(gapminder))
suppressPackageStartupMessages(library(scales))
knitr::opts_chunk$set(fig.width = 5, fig.height = 4, fig.align = "center")
```


```{r}
ggplot(gapminder, aes(gdpPercap, lifeExp)) +
  geom_point(alpha = 0.1) +
  scale_x_log10("GDP per capita", labels = scales::dollar_format()) +
  theme_bw() +
  ylab("Life Expectancy")
```


In class Practice

```{r, fig.width = 5, fig.height = 2}
gapminder %>% 
  filter(year == 2007) %>% 
  mutate(continent = fct_infreq(continent)) %>% 
  ggplot(aes(continent)) +
  geom_bar() +
  theme_bw()
```

With the output plot
| Grammar Component     | Specification |
|-----------------------|---------------|
| __data__              | `gapminder`  |
| __aesthetic mapping__ |               |
| __geometric object__  | Bar          |
| scale                 | Linear       |
| statistical transform | none         |
| coordinate system     | rectangular  |
| facetting             | none         |


Class Walkthrough of a Scatter Plot

```{r}
ggplot(gapminder, aes(gdpPerCap, lifeExp))


